# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhlGame',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='KhlGameStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_count', models.IntegerField()),
                ('reflected_count', models.IntegerField()),
                ('period_number', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.KhlGame')),
            ],
        ),
        migrations.CreateModel(
            name='KhlTeam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(choices=[('Ак Барс', 'Ак Барс'), ('Салават Юлаев', 'Салават Юлаев'), ('Трактор', 'Трактор'), ('Автомобилист', 'Автомобилист'), ('Металлург Мг', 'Металлург Мг'), ('Нефтехимик', 'Нефтехимик'), ('Авангард', 'Авангард'), ('Амур', 'Амур'), ('Торпедо', 'Торпедо'), ('Сибирь', 'Сибирь'), ('Барыс', 'Барыс'), ('Адмирал', 'Адмирал'), ('Куньлунь РС', 'Куньлунь РС'), ('СКА', 'СКА'), ('ЦСКА', 'ЦСКА'), ('Йокерит', 'Йокерит'), ('Локомотив', 'Локомотив'), ('ХК Сочи', 'ХК Сочи'), ('Спартак', 'Спартак'), ('Северсталь', 'Северсталь'), ('Динамо Мск', 'Динамо Мск'), ('Динамо Мн', 'Динамо Мн'), ('Витязь', 'Витязь'), ('Слован', 'Слован'), ('Динамо Р', 'Динамо Р')], help_text='Choose team', max_length=50, verbose_name='Team name')),
            ],
        ),
        migrations.CreateModel(
            name='NhlGame',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NhlGameStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_count', models.IntegerField()),
                ('reflected_count', models.IntegerField()),
                ('period_number', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.NhlGame')),
            ],
        ),
        migrations.CreateModel(
            name='NhlTeam',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(choices=[('Анахайм Дакс', 'Анахайм Дакс'), ('Бостон Брюинз', 'Бостон Брюинз'), ('Вашингтон Кэпиталз', 'Вашингтон Кэпиталз'), ('Вегас Голден Найтс', 'Вегас Голден Найтс'), ('Виннипег Джетс', 'Виннипег Джетс'), ('Коламбус Блю Джекетс', 'Коламбус Блю Джекетс'), ('Колорадо Эвеланш', 'Колорадо Эвеланш'), ('Лос-Анджелес Кингз', 'Лос-Анджелес Кингз'), ('Миннесота Уайлд', 'Миннесота Уайлд'), ('Нью-Джерси Дэвилз', 'Нью-Джерси Дэвилз'), ('Нэшвилл Предаторз', 'Нэшвилл Предаторз'), ('Питтсбург Пингвинз', 'Питтсбург Пингвинз'), ('Сан-Хосе Шаркс', 'Сан-Хосе Шаркс'), ('Тампа-Бэй Лайтнинг', 'Тампа-Бэй Лайтнинг'), ('Торонто Мэйпл Лифс', 'Торонто Мэйпл Лифс'), ('Филадельфия Флайерз', 'Филадельфия Флайерз')], help_text='Choose team', max_length=50, verbose_name='Team name')),
            ],
        ),
        migrations.AddField(
            model_name='nhlgamestat',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.NhlTeam'),
        ),
        migrations.AddField(
            model_name='nhlgame',
            name='first_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='score.NhlTeam'),
        ),
        migrations.AddField(
            model_name='nhlgame',
            name='second_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='score.NhlTeam'),
        ),
        migrations.AddField(
            model_name='khlgamestat',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.KhlTeam'),
        ),
        migrations.AddField(
            model_name='khlgame',
            name='first_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='score.KhlTeam'),
        ),
        migrations.AddField(
            model_name='khlgame',
            name='second_team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='score.KhlTeam'),
        ),
    ]
