# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 18:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khlgame',
            name='game_data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='nhlgame',
            name='game_data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
