# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20180605_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khlgame',
            old_name='first_team_id',
            new_name='first_team_name',
        ),
        migrations.RenameField(
            model_name='khlgame',
            old_name='second_team_id',
            new_name='second_team_name',
        ),
        migrations.RenameField(
            model_name='khlgamestat',
            old_name='team_id',
            new_name='team_name',
        ),
        migrations.RemoveField(
            model_name='khlteam',
            name='id',
        ),
        migrations.AlterField(
            model_name='khlteam',
            name='team_name',
            field=models.CharField(choices=[('Ак Барс', 'Ак Барс'), ('Салават Юлаев', 'Салават Юлаев'), ('Трактор', 'Трактор'), ('Автомобилист', 'Автомобилист'), ('Металлург Мг', 'Металлург Мг'), ('Нефтехимик', 'Нефтехимик'), ('Авангард', 'Авангард'), ('Амур', 'Амур'), ('Торпедо', 'Торпедо'), ('Сибирь', 'Сибирь'), ('Барыс', 'Барыс'), ('Адмирал', 'Адмирал'), ('Куньлунь РС', 'Куньлунь РС'), ('СКА', 'СКА'), ('ЦСКА', 'ЦСКА'), ('Йокерит', 'Йокерит'), ('Локомотив', 'Локомотив'), ('ХК Сочи', 'ХК Сочи'), ('Спартак', 'Спартак'), ('Северсталь', 'Северсталь'), ('Динамо Мск', 'Динамо Мск'), ('Динамо Мн', 'Динамо Мн'), ('Витязь', 'Витязь'), ('Слован', 'Слован'), ('Динамо Р', 'Динамо Р')], help_text='Choose team', max_length=50, primary_key=True, serialize=False),
        ),
    ]
