# Generated by Django 2.0.6 on 2018-06-27 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_auto_20180613_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khlgame',
            name='first_team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='score.KhlTeam', verbose_name='имя первой команды'),
        ),
        migrations.AlterField(
            model_name='khlgame',
            name='game_data',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='khlgame',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id игры'),
        ),
        migrations.AlterField(
            model_name='khlgame',
            name='second_team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='score.KhlTeam', verbose_name='Имя второй команды'),
        ),
        migrations.AlterField(
            model_name='khlgamestat',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.KhlGame', verbose_name='id команды'),
        ),
        migrations.AlterField(
            model_name='khlgamestat',
            name='period_number',
            field=models.IntegerField(verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='khlgamestat',
            name='reflected_count',
            field=models.IntegerField(verbose_name='Отбитые броски'),
        ),
        migrations.AlterField(
            model_name='khlgamestat',
            name='shot_count',
            field=models.IntegerField(verbose_name='Броски по воротам'),
        ),
        migrations.AlterField(
            model_name='khlgamestat',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.KhlTeam', verbose_name='Имя команы'),
        ),
        migrations.AlterField(
            model_name='khlteam',
            name='team_name',
            field=models.CharField(choices=[('Ак Барс', 'Ак Барс'), ('Салават Юлаев', 'Салават Юлаев'), ('Трактор', 'Трактор'), ('Автомобилист', 'Автомобилист'), ('Металлург Мг', 'Металлург Мг'), ('Нефтехимик', 'Нефтехимик'), ('Авангард', 'Авангард'), ('Амур', 'Амур'), ('Торпедо', 'Торпедо'), ('Сибирь', 'Сибирь'), ('Барыс', 'Барыс'), ('Адмирал', 'Адмирал'), ('Куньлунь РС', 'Куньлунь РС'), ('СКА', 'СКА'), ('ЦСКА', 'ЦСКА'), ('Йокерит', 'Йокерит'), ('Локомотив', 'Локомотив'), ('ХК Сочи', 'ХК Сочи'), ('Спартак', 'Спартак'), ('Северсталь', 'Северсталь'), ('Динамо Мск', 'Динамо Мск'), ('Динамо Мн', 'Динамо Мн'), ('Витязь', 'Витязь'), ('Слован', 'Слован'), ('Динамо Р', 'Динамо Р')], help_text='Choose team', max_length=50, primary_key=True, serialize=False, verbose_name='Имя команды'),
        ),
        migrations.AlterField(
            model_name='nhlgame',
            name='first_team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='score.NhlTeam', verbose_name='Имя первой команды'),
        ),
        migrations.AlterField(
            model_name='nhlgame',
            name='game_data',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='nhlgame',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id игры'),
        ),
        migrations.AlterField(
            model_name='nhlgame',
            name='second_team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='score.NhlTeam', verbose_name='Имя второй команды'),
        ),
        migrations.AlterField(
            model_name='nhlgamestat',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.NhlGame', verbose_name='id игры'),
        ),
        migrations.AlterField(
            model_name='nhlgamestat',
            name='period_number',
            field=models.IntegerField(verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='nhlgamestat',
            name='reflected_count',
            field=models.IntegerField(verbose_name='Отбитые броски'),
        ),
        migrations.AlterField(
            model_name='nhlgamestat',
            name='shot_count',
            field=models.IntegerField(verbose_name='Броски по воротам'),
        ),
        migrations.AlterField(
            model_name='nhlgamestat',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.NhlTeam', verbose_name='Имя команды'),
        ),
        migrations.AlterField(
            model_name='nhlteam',
            name='team_name',
            field=models.CharField(choices=[('Анахайм Дакс', 'Анахайм Дакс'), ('Бостон Брюинз', 'Бостон Брюинз'), ('Вашингтон Кэпиталз', 'Вашингтон Кэпиталз'), ('Вегас Голден Найтс', 'Вегас Голден Найтс'), ('Виннипег Джетс', 'Виннипег Джетс'), ('Коламбус Блю Джекетс', 'Коламбус Блю Джекетс'), ('Колорадо Эвеланш', 'Колорадо Эвеланш'), ('Лос-Анджелес Кингз', 'Лос-Анджелес Кингз'), ('Миннесота Уайлд', 'Миннесота Уайлд'), ('Нью-Джерси Дэвилз', 'Нью-Джерси Дэвилз'), ('Нэшвилл Предаторз', 'Нэшвилл Предаторз'), ('Питтсбург Пингвинз', 'Питтсбург Пингвинз'), ('Сан-Хосе Шаркс', 'Сан-Хосе Шаркс'), ('Тампа-Бэй Лайтнинг', 'Тампа-Бэй Лайтнинг'), ('Торонто Мэйпл Лифс', 'Торонто Мэйпл Лифс'), ('Филадельфия Флайерз', 'Филадельфия Флайерз')], help_text='Choose team', max_length=50, primary_key=True, serialize=False, verbose_name='Имя команды'),
        ),
    ]
