# Generated by Django 2.0.6 on 2018-06-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_auto_20180627_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khlgame',
            options={'verbose_name': 'Игра'},
        ),
        migrations.AlterModelOptions(
            name='khlgamestat',
            options={'verbose_name': 'Статистика по игре'},
        ),
        migrations.AlterModelOptions(
            name='khlteam',
            options={'verbose_name': 'Команда'},
        ),
        migrations.AlterModelOptions(
            name='nhlgame',
            options={'verbose_name': 'Игра'},
        ),
        migrations.AlterModelOptions(
            name='nhlgamestat',
            options={'verbose_name': 'Статистика по игре'},
        ),
        migrations.AlterModelOptions(
            name='nhlteam',
            options={'verbose_name': 'Команда'},
        ),
    ]
