# Generated by Django 2.0.6 on 2018-06-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_auto_20180627_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khlgame',
            options={'verbose_name': 'Игра КХЛ', 'verbose_name_plural': 'Игры КХЛ'},
        ),
        migrations.AlterModelOptions(
            name='khlgamestat',
            options={'verbose_name': 'Статистика по игре КХЛ', 'verbose_name_plural': 'Статистика по играм КХЛ'},
        ),
        migrations.AlterModelOptions(
            name='khlteam',
            options={'verbose_name': 'Команда КХЛ', 'verbose_name_plural': 'Команды КХЛ'},
        ),
        migrations.AlterModelOptions(
            name='nhlgame',
            options={'verbose_name': 'Игра НХЛ', 'verbose_name_plural': 'Игры НХЛ'},
        ),
        migrations.AlterModelOptions(
            name='nhlgamestat',
            options={'verbose_name': 'Статистика по игре НХЛ', 'verbose_name_plural': 'Статистика по играм НХЛ'},
        ),
        migrations.AlterModelOptions(
            name='nhlteam',
            options={'verbose_name': 'Команда НХЛ', 'verbose_name_plural': 'Команды НХЛ'},
        ),
    ]
