# Generated by Django 2.0.6 on 2018-06-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0007_auto_20180627_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khlgamestat',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.KhlGame', verbose_name='id игры'),
        ),
    ]
